### ISSUE TITLE
user-management作成メモ

### ISSUE THREAD

**Issue by kavogh** [kavogh/memo#5]
- [x] InitialCommit(HelloWorld)
- [x] login/logout
- [x] simple register
- [x] simple search
- [x] dynamic search
- [x] validation seach
- [x] pagination
- [x] register confirm
- [x] validation register
- [ ] update
- [ ] delete
- [ ] 
- [ ]

**Comment by kavogh** [comment]
- InitialCommit
  - mvn archetype:generate
    http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ImplementationAtEachLayer/CreateWebApplicationProject.html
  
  ```
  mvn archetype:generate -B^
  -DarchetypeCatalog=http://repo.terasoluna.org/nexus/content/repositories/terasoluna-gfw-releases^
  -DarchetypeGroupId=org.terasoluna.gfw.blank^
  -DarchetypeArtifactId=terasoluna-gfw-multi-web-blank-mybatis3-archetype^
  -DarchetypeVersion=5.1.0.RELEASE^
  -DgroupId=com.example.todo^
  -DartifactId=user-management-t5-retry^
  -Dversion=1.0.0-SNAPSHOT
  ```
  - [test]
  - add .gitignore
  - commit

**Comment by kavogh** [comment]
- Login
  - DB setup
    - install H2DB
      - http://www.h2database.com/html/main.html
      - http://www.h2database.com/html/grammar.html
    - create schema
    - create data
    - [test]
  - dom-layer
    - make Account class
      -  add dep Lombok http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/Appendix/Lombok.html
    - make AccountRepository IF & SQL mapper xml with findOne method(incomp)
    - make AccountSharedService/AccountSharedServiceImpl
    - make SampleUserDetails/SampleUserDetailsService
  - App-layer
    - make login/welcome jsp
    - add form-login,logout,intercept-url, authentication-manager to spr-sec.xml
    - session true
  - [test] display login/top page

**Comment by kavogh** [comment]
問題
- usernameがprimaryなのが違和感。usernameという名称を変更したい。SpringSecとの兼ね合いを調べる必要がある。displaynameを入れて妥協。
- SQLをなるべく低レベルから動作確認する方法。H2コンソールでは値代入、複数SQLIDの連結、結果受け取りがテストできない。
- ROLE_USERでいいのか
- import javax.inject.Inject;
- @RequestMapping でmethodを指定する必要性について http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ImplementationAtEachLayer/ApplicationLayer.html#controller-mapping-label
- Date型どれ？
- Account/Userの名称の混在。本当はUserで統一したいのであるが、SpringのUserクラスがあるためにAccountとした。しかしリクエストマッピング要件ではUser/userという名称が含まれ、それに従うため混在が起きた。
- 動作中のH2DBの中身を簡単に確認する方法。ポート番号がわかればブラウザからコンソール叩けそうだが。
- ボタンのjspの違いとは。
- 大文字小文字の違いの意識
- like, %, #{}の併用の記述方法。どこに載ってる？
- SQL生成文
  - JSPでvalueを設定すると空文字が入ってしまう。
  - "criteria.username != null and criteria.username != ''" のように空文字も弾かないと有害・ムダなAND文が生まれる。一致なら='',LIKEならLIKE '%%'のような。
  - でも本当は複雑にしたくない。
  - ２つ<if>をならべるとき、ANDは必須である。先頭がANDから始まる場合は、削れられるので問題ない。（ログで確認できる。）
- 登録時、accountの中身の準備はコントローラですべきか、サービスですべきか。
  - http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ImplementationAtEachLayer/DomainLayer.html#id17
  - http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ImplementationAtEachLayer/ApplicationLayer.html#id120
  - 更新時刻、デフォルトの値。updatedAt,state=INIT,...

**Comment by kavogh** [comment]
- simple register
  - add empty SCRs
    - RegisterUserController/JSPs(only submit button)
  - add Form class and form tags
    - only String elements
  - make SQL xml & repoIF
    - write SQL and H2 console test
  - rev Service, Controller
  - impl simple insert
    - check on H2 Console　できない・・・

**Comment by kavogh** [comment]
insert into account(    username ,displayname,    password,    birthday,    address,    telnum ,    roles  ,    status )
values('0002','0002','0002','1999-11-11','0002','0002','0002','0002');

**Comment by kavogh** [comment]
後回しにしたことリスト
- [x] form,entityの項目が一部のみ
- [x] register confirm
- [x] validation
- [x] 検索条件
- [x] redo
- [ ] role
- [ ] state
- [ ] 各カラムのディティール
- [ ] usernameの自動割当
- [ ] password conf
- [x] session scope
- [x] confirm
- [x] RGP
- [ ] indent, formatter, cleaning
- [ ] 適切な型
- [ ] RMVDユーザをデフォルトで表示しない
- [ ] 初期パスワード変更
- [ ] 認可
- [ ] 業務エラーメッセージ
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by kavogh** [comment]
- simple search (no criteria)
  - make model
    - UserSearchCriteria
  - repoIF (countByCriteria, findPageByCriteria)
    - import java.util.List;
    - import org.apache.ibatis.annotations.Param;
    - import org.springframework.data.domain.Pageable;
  - make SQL xml
    - write SQL and H2 console test
  - impl serIF,serImpl as Guideline
    -  http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/DataAccessMyBatis3.html#dataaccessmybatis3howtousefindpageusingsqlfilter
  - impl SearchUserForm
  - impl Controller
    - http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/Pagination.html#id10
  - add empty SCRs
    - form/list JSPs
    - add Pagi tags
  - [test] 穴だらけだが検索機能は動いた。登録と検索の連動を確認。

**Comment by kavogh** [comment]
- pagination

Caused by: javax.servlet.jsp.JspTagException: 直近の親タグである &lt;choose&gt; をセットせずに &lt;when&gt; スタイル・タグを使うことは正しくありません
    at org.apache.taglibs.standard.tag.common.core.WhenTagSupport.doStartTag(WhenTagSupport.java:57) ~[taglibs-standard-impl-1.2.5.jar:1.2.5]
    at org.apache.jsp.WEB_002dINF.views.user.searchList_jsp._jspx_meth_c_005fwhen_005f0(searchList_jsp.java:194) ~[na:na]
    at org.apache.jsp.WEB_002dINF.views.user.searchList_jsp._jspService(searchList_jsp.java:156) ~[na:na]
    ... 135 common frames omitted

**Comment by kavogh** [comment]
#### 省略したポイントの補完
- DB columns add
  - add TIMESTAMP updatedAt
  - rev Account
- 検索結果表示の補完
  - AccountRepository.xml
    - findPageByCriteriaで全カラム取得
    - searchList.jsp補完
- 登録フォームの補完
  - RegisterUserForm (all String)

**Comment by kavogh** [comment]
- 検索条件
  - findPageByCriteriaWherePhrase
    -  http://www.mybatis.org/mybatis-3/dynamic-sql.html
  - enable like-search

**Comment by kavogh** [comment]
- Date型
  - Stringでやる場合は？
- @RequestMappingでmethodを指定する理由は何か,paramとの比較
- return jsp.forward.redirect, call methodの使い分け
- ガイドラインのpaginationの説明構成
  - GET前提だよね？POSTの場合のやり方が書いてない気が
- `<input type="submit" name="form" value="登録" />`
  - valueがボタンに表示されるテキストとなるが、同時にform=登録としてパラメータが飛ぶ。使われないので挙動に影響はないが、余計であり見た目がよくない。
  - valueを指定しないとvalue="送信"

**Comment by kavogh** [comment]
- Register
  - input formを用意
  - スクリプトレットでrandom idをセット
- search validation
  - define/add annotations to Form
    - http://qiita.com/tossh/items/635aea9a529b9deb3038
  - rev arg for handler method
  - adapt StringTrim to alllow no input
    - http://terasolunaorg.github.io/guideline/5.1.0.RELEASE/ja/ArchitectureInDetail/Validation.html#validation-string-trimmer-editor
- pagination
  - add bootstrap
  - rev `queryTmpl="list&page={page}&size={size}"`
  - rev  to save Criteria on POST 可能？
    - Criteriaが保存される場所の候補は？1.Session 2.request(hiddenで返す) 3.パラメータ？
      - http://www.itmedia.co.jp/enterprise/0303/31/epn22_3.html
  - rev GET search(impl save Criteria with GET)
    - specify method="get" on form:form
    - add `<input name="list" />` bacause params are deleted on GET
    - add `criteriaQuery="${f:query(searchUserForm)}` on t:pagination

**Comment by kavogh** [comment]
HTTPステータス 400 - Parameter conditions "list" OR "form" not met for actual request parameters: page={1}, size={5}

type ステータスレポート

メッセージ Parameter conditions "list" OR "form" not met for actual request parameters: page={1}, size={5}

説明 The request sent by the client was syntactically incorrect.
Apache Tomcat/8.0.32

**Comment by kavogh** [comment]
todo-infra.properties で database.url=jdbc:h2:mem:(略)

jdbc:h2:file:C:/data/test

**Comment by kavogh** [comment]
[@NotNull/@NotEmpty/@NotBlankの違い](http://n-agetsuma.hatenablog.com/entry/2012/10/14/010410)

**Comment by kavogh** [comment]
- register
  - validation
  - confirm scr
  - use sessionAttr
  - separate exe&finish
  - set Time and State on Cont (or SQL)
  - rev create SQL for createdAt

**Comment by kavogh** [comment]
- params=execute executeってつけたほうが良くない？＞RM表
- ガイドラインにInvalidRequestExceptionの具体例がない。
- state,createdAtとか仕込むのどこか。

**Comment by kavogh** [comment]
- Javadoc記述。
- コーディング規約適用。Sonar適用。
- Mail発出
- テスト記述。JUnit。Selenium。
- スタイル。表組み。表示。入力ルール。
- client check
- パスワード運用設計

**Comment by kavogh** [comment]
- register
  - display UserID on regiComp page
  - trans String to Date
    - 5.2.3.2.3. Joda-Time用のTypeHandlerの実装
      - ここと http://qiita.com/mather314/items/1d0e3bb2e94283f85e96 を参考にsql.Date<>joda LocalDateを作る
    - 5.2.2.3.5. TypeHandlerの設定
    - Model/Form,jsp
    - http://qiita.com/yu_eguchi/items/5a1b2ae46ff803b020bf Integerには@NotEmptyは使えず、@NotNullを使えとのことみたい。
